- .gitignore
- .travis.yml
- ah_bootstrap.py
This should fix `python setup.py build_sphinx` for Sphinx 1.3+.
> Updated astropy-helpers to v1.0.2

- docs/reproject/index.rst
- reproject/high_level.py
- reproject/wcs_utils.py
cc @cdeil (there was one function that is not in the core that we need to keep)
> Update requirement to Astropy 1.0 and remove unused code

- .travis.yml
- reproject/healpix.py
- reproject/tests/test_healpix.py
Tool to convert HEALPIX images to Galactic or ICRS coordinates, based tightly on @cdeil's function in gammapy.  See https://github.com/healpy/healpy/issues/129.
> Add HEALPIX reprojection

- docs/reproject/index.rst
- reproject/conftest.py
- setup.cfg
This PR enables doctest and does minor housekeeping.
Atm the example file is not in this repo, but downloaded from another github repo. Do you think we should add a local copy here, too?
> Enable doctest

- reproject/healpix/core.py
- reproject/healpix/tests/test_healpix.py
- reproject/spherical_intersect/core.py
- reproject/tests/test_high_level.py
Fixes https://github.com/astrofrog/reproject/issues/23
> Make sure that we accept any input numerical types

- docs/celestial.rst
- reproject/interpolation/high_level.py
- reproject/spherical_intersect/high_level.py
A common use case will be to pass the filename to a FITS or ASDF file as the first argument.
> Add support for filename in first argument

- reproject/array_utils.py
- reproject/healpix/tests/test_healpix.py
- reproject/healpix/tests/test_utils.py
- reproject/healpix/utils.py
- reproject/spherical_intersect/core.py
- reproject/spherical_intersect/high_level.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/tests/test_utils.py
- reproject/utils.py
Now at 98%. If someone wants to have fun with the remaining 2%, please feel free to :)
> Improve coverage

- .travis.yml
- reproject/spherical_intersect/core.py
- reproject/spherical_intersect/tests/test_reproject.py
> Simplify the handling of the parallel processing in exact mode

- .travis.yml
- CHANGES.md
- reproject/interpolation/core.py
- reproject/interpolation/tests/test_core.py
Needs regression test and changelog entry, and probably a new release.
> Fix ordering of x/y in map_coordinates

- reproject/interpolation/core.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/spherical_intersect/tests/test_reproject.py
Work was collaborative with @adonath
> Generalize reprojection in 3 dimensions

- reproject/interpolation/core.py
- reproject/interpolation/high_level.py
Major issue is that WCS axis types aren't compared for consistency
> WIP: Add support for reprojecting arbitrary n-dimensional WCS using interpolation

- .gitignore
- .travis.yml
- docs/conf.py
- ez_setup.py
- setup.py
Includes the changes of configparser for py3.5.2, and a few minor things.
> Updating to package template 1.1.2

- reproject/healpix/high_level.py
- reproject/spherical_intersect/high_level.py
> Change default hdu to 0 for (assumed) image FITS hdulists

- .circleci/config.yml
- .travis.yml
- reproject/interpolation/tests/test_core.py
This also fixes https://github.com/astrofrog/reproject/issues/111
> Add 32-bit CircleCI configuration

- CHANGES.md
- reproject/utils.py
#88 Deal with the first improvement.
It seems like the second one has already been implemented.
> Improve parse_output_projection

- CHANGES.md
- reproject/healpix/utils.py
Fix https://github.com/astrofrog/reproject/issues/156
> Fix bug in auto-identification of HEALPix ordering

- reproject/_astropy_init.py
This is an automated update made by the astropy package-template ``batchpr``
tool :robot: - feel free to close if it doesn't look good!
You can report issues to @bsipocz.
> Package-template update: _astropy_init.py

- .travis.yml
- docs/index.rst
- reproject/healpix/core.py
- reproject/healpix/utils.py
- reproject/interpolation/high_level.py
- reproject/utils.py
- setup.cfg
In addition of switching to use standalone six, now I'm pushing more maintenance related commits to this PR.
> General maintanance

- docs/conf.py
- docs/reproject_interpolate_example.py
- reproject/conftest.py
- reproject/healpix/core.py
- reproject/healpix/high_level.py
- reproject/healpix/tests/test_healpix.py
- reproject/healpix/tests/test_utils.py
- reproject/healpix/utils.py
- reproject/interpolation/core.py
- reproject/interpolation/tests/test_core.py
- reproject/mosaicking/background.py
- reproject/mosaicking/coadd.py
- reproject/mosaicking/subset_array.py
- reproject/mosaicking/tests/test_background.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/mosaicking/tests/test_subset_array.py
- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
- reproject/spherical_intersect/high_level.py
- reproject/spherical_intersect/overlap.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/spherical_intersect/tests/test_overlap.py
- reproject/spherical_intersect/tests/test_reproject.py
- reproject/tests/test_high_level.py
- reproject/tests/test_utils.py
- reproject/utils.py
- reproject/wcs_utils.py
- setup.cfg
This sorts imports using isort and removes remaining ``__future__`` imports
> Clean up imports

- reproject/interpolation/high_level.py
@keflavich - I think this should help fix the issues you were seeing in spectral-cube.
> Properly deprecate independent_celestial_slices

- docs/index.rst
- reproject/adaptive/high_level.py
- reproject/interpolation/high_level.py
- reproject/spherical_intersect/high_level.py
- reproject/tests/test_utils.py
- reproject/utils.py
- setup.cfg
Also some other tweaks as I write sunpy docs.
> This is a second, much simpler attempt at allowing nddata as input

- azure-pipelines.yml
- reproject/adaptive/tests/test_core.py
- reproject/interpolation/tests/test_core.py
- setup.cfg
- tox.ini
This includes more test dependencies to make sure that all the tests are run
> Try and make sure all tests are run in CI

- docs/celestial.rst
- reproject/spherical_intersect/core.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/spherical_intersect/tests/test_reproject.py
As discovered in #199, there are precision issues for very high resolution images.
This also removes some old legacy code.
> Warn about precision issues with reproject_exact

- azure-pipelines.yml
I forgot these in the v0.6 release
> Enable 32-bit wheels

- azure-pipelines.yml
- pyproject.toml
- reproject/conftest.py
- setup.cfg
- setup.py
If this works I'll need to make sure we build these for v0.6
> Enable Python 3.8 wheels

- reproject/adaptive/high_level.py
- reproject/interpolation/high_level.py
- reproject/mosaicking/coadd.py
- reproject/spherical_intersect/high_level.py
This fixes a few issues identified with the docstrings
> Fixes to docstrings

- CHANGES.md
- docs/mosaicking.rst
- reproject/adaptive/tests/test_core.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/spherical_intersect/core.py
- reproject/spherical_intersect/high_level.py
This should fix compatibility with astropy 4.0.1
> Fix use of @deprecated_renamed_argument

- azure-pipelines.yml
- docs/mosaicking.rst
- setup.cfg
- tox.ini
We are only compatible with SciPy 1.1+
> Added oldestdeps tox environment and update minimum required version of SciPy

- docs/installation.rst
Similar to astropy/astropy#11111
cc @mwcraig
> DOC: Replace astropy channel with conda-forge

- CHANGES.md
- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/utils.py
Fixes https://github.com/astropy/reproject/issues/230
> Fix implementation of hdu_weights

- .github/workflows/ci_workflows.yml
- azure-pipelines.yml
- tox.ini
If my fork won't run the Actions properly, I might have to YOLO this one and fix later. Prerequisite for #226.
> TST: Move CI from Azure to Actions

- .github/workflows/ci_workflows.yml
- README.rst
- reproject/conftest.py
- reproject/healpix/tests/test_utils.py
- reproject/healpix/utils.py
- reproject/interpolation/tests/test_core.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/tests/test_utils.py
- reproject/utils.py
- setup.cfg
- tox.ini
> TST: Fix and update CI

- reproject/adaptive/tests/test_core.py
- reproject/interpolation/tests/test_core.py
Ignore #270 for now because I like my coffee black and my badges green.
> TST: Ignore asdf warning for devdeps

- .github/workflows/ci_workflows.yml
- pyproject.toml
- setup.cfg
- tox.ini
This may fix the Python 3.11 wheel builds
> Update pinned version of Cython

- reproject/interpolation/tests/test_core.py
> Mark tests that use remote data

- reproject/adaptive/tests/test_core.py
- reproject/array_utils.py
- reproject/conftest.py
- reproject/healpix/tests/test_healpix.py
- reproject/healpix/tests/test_utils.py
- reproject/interpolation/tests/test_core.py
- reproject/mosaicking/background.py
- reproject/mosaicking/coadd.py
- reproject/mosaicking/subset_array.py
- reproject/mosaicking/tests/test_background.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/mosaicking/tests/test_subset_array.py
- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
- reproject/spherical_intersect/core.py
- reproject/spherical_intersect/setup_package.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/spherical_intersect/tests/test_overlap.py
- reproject/spherical_intersect/tests/test_reproject.py
- reproject/tests/test_high_level.py
- reproject/tests/test_utils.py
- reproject/utils.py
- reproject/wcs_utils.py
This must have been failing because a new version of black
> Fix code style

- CHANGES.md
- reproject/adaptive/tests/test_core.py
Slight increase to tolerance to accommodate new Numpy versions
Fixes https://github.com/astropy/reproject/issues/359
> Fix tests against developer versions of packages

- pyproject.toml
> Enable Python 3.12 wheel building

- .github/workflows/ci_workflows.yml
I'll probably need to figure out how to install the dev versions of runtime dependencies for tests to pass
> Add configuration for nightly wheels

- .github/workflows/ci_workflows.yml
- .readthedocs.yaml
- pyproject.toml
- reproject/healpix/utils.py
- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
- reproject/tests/test_utils.py
- reproject/utils.py
- tox.ini
This should now work - let's see if it passes!
> Enable testing of wheels on silicon mac

- pyproject.toml
- tox.ini
Check if this fixes the oldestdeps job
> Bump minimum required version of astropy-healpix

- docs/performance.rst
- docs/performance_mosaicking.rst
- reproject/adaptive/high_level.py
- reproject/common.py
- reproject/interpolation/high_level.py
- reproject/spherical_intersect/high_level.py
- reproject/utils.py
This also includes other more general performance improvements.
> Improvements to performance when using dask.distributed

- CHANGES.md
- reproject/common.py
> Enforce readonly mode for memmap when reading input array

- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
Just a small fix after some real-world tests
> FIx issue with co-adding with broadcasting with images that have inhomogeneous footprints

- pyproject.toml
- tox.ini
There were a few dependencies missing oldest versions
> Pin more oldest dependencies
