astropy/reproject

- .travis.yml
- docs/index.rst
@astrofrog I saw that you used `@pytest.mark.importorskip('healpy')` here
https://github.com/astrofrog/reproject/blob/dd3086eab4802749d8cd70a55ca920d70a6e0d77/reproject/healpix/tests/test_healpix.py#L40
and wanted to use this in Gammapy, but it doesn't work:
https://travis-ci.org/gammapy/gammapy/jobs/61290205#L907
https://github.com/gammapy/gammapy/pull/258
This also doesn't work for me locally ... is this the correct way to use this mark?
Maybe the `reproject` tests on travis-ci don't fail just because there's no build where healpy is not available:
https://github.com/astrofrog/reproject/blob/master/.travis.yml#L96
I guess that should be added.
> Add travis-ci build without optional dependencies

- appveyor.yml
- reproject/spherical_intersect/mNaN.h
- reproject/spherical_intersect/overlapArea.c
- reproject/spherical_intersect/reproject_slice_c.c
- reproject/spherical_intersect/tests/test_reproject.py
@astrofrog -- this will require you to flip the switch on appveyor.
Right now this uses `ci-helpers` for appveyor but not travis...I assume I should switch travis to that also before this is merged (which would mean not merging #91 I assume).
> Patch C to compile on Windows and add appveyor testing

- reproject/healpix/high_level.py
Great package!  Would be great to be able to specify which column of a HEALPIX file to read.  This appears to be the "field" parameter in parse_input_healpix_data.  For the Planck foreground component images (I'm interested in the CO) the additional columns can be important.
If you do release an update, do I just repeat the "pip install --user reproject.py" (I'm using macports).  Or is there an update command?
Thanks,
Tony
> Read other columns of HEALPIX image?

- CHANGES.md
- reproject/interpolation/core.py
When dealing with large input images, we now make sure that we never force the whole image to be read (when memory-mapped) if only a small region is needed.
@pllim - this should fix the memory issues you were seeing. Can you install reproject from my branch to check if it works correctly, and once we've confirmed this I can go ahead and merge (if tests pass)
> Significant improvements to performance for interpolation

- reproject/interpolation/high_level.py
It looks to me like ``mode`` is from an earlier version, but there is no ``mode`` argument now.
> remove mention of mode from reproject_interp docstring

- README.md
- docs/healpix.rst
- docs/index.rst
- setup.cfg
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- .travis.yml
- appveyor.yml
Probably we need to wait a bit more until all the dependencies become available on python 3.6.
> Adding python 3.6 to CI builds

- reproject/conftest.py
Stricter `warnings_to_ignore_entire_module` to only ignore deprecation warnings from `astropy.io.fits`. If this works, it has a lower chance of accidentally ignoring other deprecation warnings that you care about.
> [EXP] Stricter warnings_to_ignore_entire_module

- .travis.yml
- appveyor.yml
- docs/index.rst
- reproject/compat.py
- reproject/mosaicking.py
- reproject/tests/test_mosaicking.py
- reproject/tests/test_wcs_utils.py
- reproject/utils.py
- reproject/wcs_utils.py
This adds a new function for determining the optimal WCS/shape for a mosaic of images (or for a single image if changing coordinate frame). This is an alternative to the implementation of a a similar function in https://github.com/astrofrog/reproject/pull/125, but the version here takes into account different coordinate frames and can automatically rotate images if needed.
What is missing here compared to https://github.com/astrofrog/reproject/pull/125 is that we should use the minimal image excluding NaNs as input rather than the full images.
> New function for determining optimal WCS/shape for set of images

- .travis.yml
- CHANGES.md
- docs/celestial.rst
- reproject/interpolation/core_celestial.py
- reproject/interpolation/core_full.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
When projecting very large cubes with independent celestial slices, it should be possible - in principle - to specify an output array that is a memory map on disk and write into that, thereby avoiding ever having the whole cube in memory.  
In practice, my first attempt with this failed.  I don't understand why yet, but I vaguely suspect that some interaction between the OS and python isn't capable enough to put the already-completed data aside...
> Support large cube reprojection via 'out' arrays

- docs/celestial.rst
see https://reproject.readthedocs.io/en/latest/celestial.html#very-large-cubes.  The problem was having `::` before the `.. doctest-skip::` directive.
> Fix malformatted .. doctest-skip:: directives in Very Large Cubes docs

- .travis.yml
- ah_bootstrap.py
- appveyor.yml
This is an automated update of the astropy-helpers submodule to v3.2.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
Please note that since v3.2, ``sphinx-astropy`` needs to be explicitely listed as a dependency for building the documentation. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v3.2.1/CHANGES.rst). 
We also wanted to let you know that we have made new releases of the astropy package-template. You can find the latest [cookiecutter template here](https://github.com/astropy/package-template) or if you prefer you can find a [rendered version of the template here](https://github.com/astropy/package-template/tree/master). 
*This is intended to be helpful, but if …
> Update astropy-helpers to v3.2.1

- .circleci/config.yml
- CHANGES.md
- reproject/spherical_intersect/overlap.py
- reproject/spherical_intersect/overlapArea.c
- reproject/spherical_intersect/tests/test_overlap.py
- reproject/spherical_intersect/tests/test_reproject.py
This should fix the bug that has been reported a few times relating to WCSes with non-standard orientations (e.g. with E and W flipped). This was due to the ``overlapArea`` function not working correctly with clockwise spherical polygons.
Fixes #113 (checked)
Fixes #164 (checked)
Fixes #187 (checked)
> Fix bug in exact mode related to WCS orientation

- reproject/conftest.py
Currently astropy 2.0+ is required, and also the 0.2 version of pytest-arraydiff fixed their deprecated astropy.io.fits usage, thus some cleanup could be done.
> Minor conftest.py cleanup

- reproject/mosaicking/coadd.py
Fixes https://github.com/astropy/reproject/issues/194
This will then magically work with APE 14 WCSes once Astropy 4.0 is out.
> Use slicing notation for compatibility with APE14 WCS

- reproject/interpolation/core.py
This is purely a code aesthetic change, but I think it makes it much more readable with the validation split off into it's own function.
> Split out interpolation WCS validation into new function

- CHANGES.md
- azure-pipelines.yml
- docs/installation.rst
- docs/mosaicking.rst
- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
- reproject/tests/test_utils.py
- reproject/utils.py
- setup.cfg
For `find_optimal_celestial_wcs`, we only really need the input image shape, not the actual data. Modify the support infrastructure to allow computation in this regime. This allows us to solve for the optimal WCS even in cases where we wouldn't be able to hold all of the input images in memory at the same time.
> Allow WCS merging to work without loading all data at once

- reproject/_astropy_init.py
This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497
> MNT: Remove unused astropy config code

- reproject/mosaicking/coadd.py
The argument is called `reproject_function`, not `reprojection_function`.
> Fix typo in exception message

- reproject/adaptive/core.py
xref https://github.com/astropy/reproject/issues/195 - I would have missed this behaviour warning if I wasn't looking through github issues, so it would probably be prudent to add a warning to the docs.
> Add warning to docs about edge nans in adaptive method

- reproject/spherical_intersect/setup_package.py
`distutils` is deprecated.
This package does not seem to be affected by astropy/astropy#12633.
> MNT: Stop using distutils

- reproject/interpolation/core.py
- reproject/interpolation/high_level.py
- reproject/wcs_utils.py
I wrote these as I was reading the code trying to understand how `reproject_interp` works, and thought they were worth adding.
> Add some more docs for reproject_interp

- .github/workflows/ci_workflows.yml
- README.rst
- setup.cfg
From #271 because that PR might take a while and these should be uncontroversial. I'll rebase that PR once this is in.
> MNT: General clean-up

- tox.ini
The multiprocessing bug should be gone now.
Fix #280 , undo #277
> TST: Unpin coverage to grab 6.4

- CHANGES.md
- docs/celestial.rst
- reproject/adaptive/core.py
- reproject/adaptive/deforest.pyx
- reproject/adaptive/high_level.py
- reproject/adaptive/tests/test_core.py
I lied, here's a fourth PR, applying on top of #276. The two commits belong to this PR are "Add boundary handling..." and "Set default boundary mode...".
This adds a few different boundary-handling modes, to adjust how the adaptive resampling algorithm handles the case when the sampling window straddles or lies outside of the boundary of the input image---that is, when some of the input pixels that should be sampled for a given output pixel do not exist. The existing behavior was to simply ignore those out-of-bounds samples and base the output pixel value on the remaining in-bounds samples (or set the output to NaN if there are no in-bounds samples), and that can give rise to some strong edge effects, depending on the input image. The old behavior can be had with the "ignore" mode in this …
> Add boundary handling options for adaptive resampling

- reproject/adaptive/high_level.py
- reproject/adaptive/tests/test_core.py
- reproject/tests/test_high_level.py
(One new commit on top of the boundary-handling PR, will rebase later)
This warns the user if the default filter kernel or boundary handling mode is being used.
```
In [3]: reproject.reproject_adaptive((data, w), w, data.shape)
<ipython-input-3-6fbe9b99ba1d>:1: FutureWarning: The default kernel will change from 'Hann' to  'Gaussian' in a future release. To suppress this warning, explicitly select a kernel with the 'kernel' argument.
reproject.reproject_adaptive((data, w), w, data.shape)
<ipython-input-3-6fbe9b99ba1d>:1: FutureWarning: The default boundary mode will change from 'ignore' to  'strict' in a future release. To suppress this warning, explicitly select a mode with the 'boundary_mode' argument.
reproject.reproject_adaptive((data, w), w, data.shape)
Out[3]: 
...
In [4]: …
```
> Warn about future changes to adaptive defaults

- .github/workflows/ci_workflows.yml
Numpy and pyyaml are not publishing wheels for 32bit any more, so our build timesout.
> Remove the 32bit wheel build

- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/utils.py
Performing reprojection of any non-healpix type by breaking up the out space into blocks and iterating over each block to perform reprojection into that specific block of area. This means a large output space can be used whilst only having to load one block into memory at a time. 
Additionally these output blocks can be processed in parallel to achieve a speed up of any function. 
As mentioned there is still some debug code in there which needs to be cleaned up (commented print statement, imports used for profiling), but the functionality is there.
> Add support for blocked and parallel reprojection in ``reproject_interp``

- docs/celestial.rst
- reproject/adaptive/core.py
- reproject/adaptive/deforest.pyx
- reproject/adaptive/high_level.py
- reproject/adaptive/tests/test_core.py
- reproject/tests/test_high_level.py
Split from #276 
This PR changes the defaults for `reproject_adaptive` to use the Gaussian kernel, with the Hann left as an option. This is the most significant change in this PR series, as anyone using `reproject_adaptive` in their code will see very different results after updating to a version of `reproject` with this change. Their output images will be a bit blurrier, but better anti-aliased. (To be sure, every output image will also change due to the bug fixes, though those changes will hopefully be much smaller.) I'll argue that making this kernel the default is the right choice, though, because it strengthens the anti-aliasing quite a bit, and that anti-aliasing is what sets this algorithm apart from the interpolating and exact algorithms. Using the Gaussian by default offers the …
> Changed default filter kernel and boundary mode in ``reproject_adaptive``, and removed ``order`` argument.

- pyproject.toml
Tests run for hours on Linux aarch64 due to the emulation, so we skip these for now (tests are already skipped for arm64 on MacOS X)
> Skip wheel tests on manylinux_aarch64

- reproject/adaptive/core.py
- reproject/interpolation/core.py
- reproject/wcs_utils.py
This is available since astropy 4.0, which is our minimum required version
> Use pixel_to_pixel from astropy.wcs.utils

- reproject/interpolation/tests/test_core.py
This seems to speed up the total execution of tests from 150s to 100s on my machine.
> Speed up test_blocked_against_single by increasing smallest block size

- reproject/healpix/high_level.py
- reproject/healpix/tests/test_utils.py
- reproject/interpolation/tests/test_core.py
- reproject/mosaicking/coadd.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/tests/test_utils.py
- reproject/utils.py
Noticed another little thing---a commit a few months ago auto-reformatted the code with Black. Black must have been imposing a new, larger maximum line length and it reflowed some strings that had been broken across multiple lines, but it left extra quotation marks in place while it did that
(CI failure appears to be pre-existing)
> Fix weird quotation marks from Black auto-formatting

- reproject/tests/test_utils.py
- reproject/utils.py
I noticed a comment pointing out that when FITS file names are passed for the input data, the file is opened but never closed. Changing that looked like a quick fix, and should be safe---after the file is opened, `parse_input_data` calls itself a few times before eventually extracting the `.data` and `.header` attributes of the selected HDU and returning those, so the HDUL object never leaves `parse_input_data`. (Not sure if the garbage collector would have eventually closed everything anyway.)
While checking that this was covered by existing tests, I saw that the `parse_input_data` tests were checking the data array that gets returned but not the corresponding WCS, so I augmented those tests to check both.
(The CI failure appears to be pre-existing)
> Close fits files after loading

- docs/celestial.rst
- reproject/adaptive/core.py
- reproject/adaptive/deforest.pyx
- reproject/adaptive/high_level.py
- reproject/adaptive/tests/test_core.py
- reproject/interpolation/core.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/spherical_intersect/core.py
- reproject/spherical_intersect/high_level.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/tests/test_high_level.py
- reproject/utils.py
This addresses #296. @entaylor, want to take a look?
This PR adds support for reprojecting multiple images that share the exact same coordinate information---e.g. a data array and a corresponding error array, or an L1 and L2 image pair. By providing multiple images in one reproject call, the coordinate transformation work can be done only once before reprojecting each image, offering a speedup.
I chose the syntax of
```python
data, header = fits.getdata('data.fits', header=True)
uncertainty = fits.getdata('uncertainty.fits')
header_out = [...]
image_stack = np.stack((data, uncertainty))
reproject.reproject_adaptive((image_stack, header), header_out)
```
i.e. multiple images passed as an extra input array dimension. There's no support for doing this by passing some sort of mult-HDU FITS …
> Add support for efficiently reprojecting multiple images with the same wcs

- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
@pllim - could you try this out with GWCS instances?
Fix #328
> Add support for APE 14 WCSes in find_optimal_celestial_wcs

- docs/installation.rst
- reproject/adaptive/high_level.py
- reproject/conftest.py
- reproject/interpolation/high_level.py
- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
- reproject/spherical_intersect/high_level.py
- reproject/tests/helpers.py
- reproject/tests/test_utils.py
- reproject/utils.py
- setup.cfg
- tox.ini
Still to do:
Fixes https://github.com/astropy/reproject/issues/323
> Allow single inputs to find_optimal_celestial_wcs and add ability to specify HDU

- reproject/adaptive/high_level.py
- reproject/adaptive/tests/test_core.py
- reproject/conftest.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
- reproject/spherical_intersect/high_level.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/tests/helpers.py
- reproject/tests/test_utils.py
- reproject/utils.py
This also refactors output_projection tests to use a fixture.
Fixes https://github.com/astropy/reproject/issues/309
> Add support for specifying output projection as APE 14 WCS with array_shape defined

- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
> Fixes for solar frames and non-degree units

- setup.cfg
Looks like they have wheels for all platforms now so we could even require it in future - but for now just at least making an 'all' extras
> Add a new 'all' extras for shapely

- reproject/array_utils.py
- reproject/conftest.py
- reproject/interpolation/high_level.py
- reproject/tests/test_array_utils.py
- reproject/tests/test_utils.py
- reproject/utils.py
This PR adds support for specifying the input data as a dask array - this covers only the general case mentioned in  https://github.com/astropy/reproject/issues/362 of **Input where all dimensions are to be reprojected**
As mentioned in #362, the general case requires us to write out the dask array to disk and reload it as a Numpy memmap array. There will be ways of making common use cases more efficient as outlined in #362 but for now this PR implements the general approach.
> Started adding support for allowing dask arrays as input

- docs/celestial.rst
- reproject/adaptive/core.py
- reproject/adaptive/deforest.pyx
- reproject/adaptive/high_level.py
- reproject/adaptive/tests/test_core.py
This adds an option to smooth over numerical quirkiness when, for example, the longitude wraps around in an all-sky map. The quirk occurs when computing the Jacobian, which is d(input-image pixel) / d(output-image pixel). This is done by finite differences, so when the input coordinates jump from one side of the map to the other, the Jacobian comes out extremely large, despite the actual transformation being unremarkable at that location. The new option looks for outlier Jacobian values, measured relative to a 3x3 local neighborhood, and replaces those outliers with a mean of the non-outlier values in the neighborhood.
Before this PR, the extremely-large Jacobian would cause the input-image region that is to be sampled to be extremely large---larger than a safety-valve threshold in the …
> Add despike_jacobian option for adaptive resampling

- reproject/conftest.py
- reproject/utils.py
> Fix support for NDData objects with dask .data attributes

- reproject/utils.py
This is a work in progress as I try and improve the performance of the parallelization
Issues I'm still seeing:
* When using the progress bar, for some reason it stays stuck at low values and then very quickly fills up to 100%, whereas normally to_zarr should really just operate chunk by chunk. This might be to do with returning the footprint and array and also the trimming of the image, which might add a layer of chunks to the whole thing. To be investigated.
* We should really clean up *all* temp files as it's easy to fill one's /tmp directory otherwise
Performance notes:
* I have tried reprojecting a (32000, 8600) array to a similar WCS and when using parallel mode, it is quite a bit faster (56 seconds with 16 processes, instead of 4m26s in synchronous mode). When using (2048, 2048) …
> Dask support improvements

- docs/mosaicking.rst
This PR fixes inadvertent rendering of
```
.. doctest-requires:: pyvo
```
in the docs.  See https://reproject.readthedocs.io/en/stable/mosaicking.html
> Fix docs mosaic page rendering

- docs/celestial.rst
- docs/dask.rst
- docs/index.rst
- reproject/adaptive/core.py
- reproject/adaptive/high_level.py
- reproject/common.py
- reproject/interpolation/core.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/spherical_intersect/core.py
- reproject/spherical_intersect/high_level.py
- reproject/spherical_intersect/tests/test_high_level.py
- reproject/spherical_intersect/tests/test_reproject.py
- reproject/tests/test_utils.py
- reproject/utils.py
- setup.cfg
- tox.ini
This refactors the handling of blocked/parallel reprojection with dask following a conversation with @Cadair.
> Refactor blocked/parallel reprojection

- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
Again with WISPR and `reproject_and_coadd`, merging the image data in the overlap region isn't the most desirable thing to do, for two reasons. First, the WISPR L3 images don't always have a well-matched background level (because of how much processing it takes to get to L3), so at the small overlap region between the two FOVs, taking a mean of the two images gives a visible seam on either side. Second, there's sometimes a time offset between images from the two images, so if I'm building the composite in HPC coordinates, the stars are offset by a few pixels and produce ghosting in the overlap region. (If I build the composite in RA/Dec coordinates, that should stop being a problem, but then I need to think about how that offsets the coronal structures and how to make an HPC WCS for my …
> Add 'first' and 'last' moasicking modes to reproject_and_coadd

- reproject/mosaicking/coadd.py
I'm trying out `reproject_and_coadd` (thanks @Cadair!). I'm making composite images from two WISPR images, which is together a pretty wide FOV (~100 degrees across). One of the two images is convex in the output projection, so checking where the image's corners fall in the output image isn't enough to properly bound it.
I've changed the function to put ten points along each edge of the image and use those to find its bounds in the output image, rather than just checking the corners. For my use-case, ten points per edge works just as well as doing every edge pixel.
Looking at just the footprint of the reprojected images, it's the difference between this (note the left edge):
and this:
> Use more points to find image bounds in moasics

- docs/celestial.rst
- reproject/adaptive/core.py
- reproject/adaptive/deforest.pyx
- reproject/adaptive/high_level.py
- reproject/adaptive/tests/test_core.py
I found myself reprojecting images with NaNs and infs, so I added a few modes for how to deal with them. The default remains the previous behavior, which just propagates these values with no special handling.
The `constant` mode isn't strictly necessary, as one could use `np.nan_to_num` on the input array before reprojecting, but implementing this in `reproject` avoids having to copy the array---maybe that's important for `dask` use cases.
> Add modes for nan and inf handling to adaptive algo

- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
Hi, 
I implemented a new combine function to compute the 2D maximum across the arrays/images to be mosaicked. It is helpful for PSF calculations, for instance.
It is a pretty straightforward addition.
Cheers.
Fabian
> Added new combine function to compute the minimum and maximum

- pyproject.toml
These error for now as other packages aren't compatible
> Skip Python 3.12 wheels

- CHANGES.md
- reproject/mosaicking/tests/test_coadd.py
On i386, this test [resulted in a failure](https://salsa.debian.org/debian-astro-team/reproject/-/jobs/4673706) because of relative differences ~2e-16. As floats are compared, minimal floating point differences my appear. This PR replaces the strict equal with an allclose test.
> Fix TestReprojectAndCoAdd failure on i386

- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
This extracts part of https://github.com/astropy/reproject/pull/351
> Add ability to specify output array and footprint in reproject_and_coadd

- pyproject.toml
- reproject/adaptive/deforest.pyx
This fixes an issue when compiling with Cython 3.0.2 and updates the pin.
> Fix compatibility with Cython 3.0.2 and update version in pyproject.toml

- reproject/common.py
- reproject/interpolation/tests/test_core.py
@keflavich - this is a fix for the issue we were seeing. Note that we need to keep the temporary directory around for a while because the user might call compute multiple times etc. So I think we might just need to document how to clean up the temporary directory once it is no longer needed.
> Fixed a bug that caused reprojected dask arrays to not be computable due to a temporary directory being removed

- .pre-commit-config.yaml
- pyproject.toml
- reproject/adaptive/high_level.py
- reproject/common.py
- reproject/healpix/high_level.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/mosaicking/background.py
- reproject/mosaicking/coadd.py
- reproject/mosaicking/subset_array.py
- reproject/mosaicking/wcs_helpers.py
- reproject/spherical_intersect/high_level.py
This enables the [numpydoc pre-commit hook](https://numpydoc.readthedocs.io/en/latest/validation.html) and fixes issues found as a result.
I've also added the ability to specify ``block_size='auto'`` so that users can opt in to blocked reprojection without having to specify an actual block size or setting ``parallel=True``.
> Added ability to set ``block_size='auto'`` and fix missing parameters in docstrings

- .github/workflows/ci_workflows.yml
- docs/mosaicking.rst
- reproject/mosaicking/tests/test_wcs_helpers.py
- setup.cfg
- tox.ini
Pulled out of https://github.com/astropy/reproject/pull/399 for easier review.
> Add tests on Python 3.11

- .github/workflows/ci_workflows.yml
- pyproject.toml
- tox.ini
I can get this building locally fine on Python 3.12 (using `python -m build`), but can reproduce the tox failure. so I think the issue must be somehow `tox` is installing a different and older version of `Cython` when trying to build `reproject`. I'm a bit lost on how to debug that though...
Update: if I remove `aiohttp` from the deps (that is also trying and failing to build a wheel due to Cython issues) this works fine. So I guess there's some dogy Cython version interaction going on somewhere... I think the answer here is to wait for `aiohttp` to get a new version out with 3.12 support and hopefully this will Just Work ™️ after that.
> Add testing on Python 3.12

- reproject/adaptive/high_level.py
- reproject/interpolation/high_level.py
- reproject/mosaicking/coadd.py
- reproject/spherical_intersect/high_level.py
Fixes https://github.com/astropy/reproject/issues/406
cc @DanRyanIrish
> Updated docstrings for output_projection and shape_out to indicate that any APE-14 WCS is acceptable

- CHANGES.md
- reproject/healpix/high_level.py
- reproject/healpix/tests/test_healpix.py
This also updates the docstrings for these functions to mention any valid APE-14 WCS is ok.
> Add tests for full range of inputs/outputs in healpix functions

- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
I'm using `reproject_and_coadd` in a  loop---in some iterations, there's only one input image (while in others, there are multiple). When I set `match_background=True`, I get some warnings and the whole output image is `nan`. Maybe this indicates a deeper problem in the background-matching code, but as a workaround, we can just not do the bg-matching if there's only a single input image, to work around this bug and avoid some extra work.
```python
import numpy as np
import reproject
import reproject.mosaicking
import matplotlib.pyplot as plt
from astropy.wcs import WCS
data = np.ones((100, 100))
data[::5] = 2
wcs_in = WCS(naxis=2)
wcs_in.wcs.ctype = 'RA---TAN', 'DEC--TAN'
wcs_in.wcs.crpix = 50, 50
wcs_in.wcs.crval = 0, 0
wcs_in.wcs.cdelt = .1, .1
wcs_out = wcs_in.deepcopy()
reprojected, …
```
> Ensure reproject_and_coadd handles bg-matching with one input image

- reproject/adaptive/deforest.pyx
Fixes  #416
Implements Cython's suggested performance fixes and removes the "performance hint" warnings. Looks like [new behavior in Cython 3.0](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept), to ensure proper handling if a Python exception is raised within a function. Since these subroutines don't call any Python code directly, no Python exception can be raised, so we can add `noexcept` flags and avoid Cython checking for an exception after every function call. These changes gain a bit of speed in a real-world benchmark, but it looks like just speed that we lost when changing to Cython 3.
I also fixed a few warnings (removed an unused function, compiler worried about an uninitialized variable, [explicitly set `language_level` …
> Fix Cython warnings

- pyproject.toml
- reproject/adaptive/deforest.pyx
- tox.ini
This is needed since astropy dev is now built against numpy dev which has some API breakage ahead of 2.0
> Fix devdeps job

- .github/workflows/ci_workflows.yml
- pyproject.toml
We need to release new wheels of reproject compiled against Numpy 2.0.0rc1 ahead of the final Numpy 2.0.0 release, so this PR updates the build-time dependencies and also simplifies the nightly wheels configuration.
> Build against Numpy 2.0.0rc1 or later

- pyproject.toml
- reproject/common.py
- reproject/tests/test_high_level.py
To run just the relevant test:
```
tox -e test -- -k "test_dask_scheduler"
```
This currently shows three test failures:
```
FAILED ../../.tox/test/lib/python3.11/site-packages/reproject/tests/test_high_level.py::test_dask_schedulers[threads-reproject_interp] - AssertionError: 
FAILED ../../.tox/test/lib/python3.11/site-packages/reproject/tests/test_high_level.py::test_dask_schedulers[threads-reproject_adaptive] - AssertionError: 
FAILED ../../.tox/test/lib/python3.11/site-packages/reproject/tests/test_high_level.py::test_dask_schedulers[threads-reproject_exact] - AssertionError: 
```
To run just one of the parameter combinations of the test, one can do e.g.:
```
tox -e test -- -k "test_dask_sched and interp and threads"
```
> Fix multi-threaded reprojection when using Astropy WCS

- reproject/array_utils.py
- reproject/mosaicking/coadd.py
- reproject/mosaicking/subset_array.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/mosaicking/tests/test_subset_array.py
- reproject/utils.py
This enables memmap'd output, which will be needed for very large (greater-than-memory) output cubes
EDIT: it also extends `reproject_and_coadd` into three dimensions
> Generalize reproject_and_coadd for N-dimensional data, and add option to specify blank pixel value and progress bar

- docs/index.rst
- docs/performance.rst
- docs/performance_mosaicking.rst
- reproject/array_utils.py
- reproject/common.py
- reproject/interpolation/core.py
- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/spherical_intersect/core.py
- reproject/tests/test_array_utils.py
- reproject/tests/test_utils.py
- reproject/utils.py
This is a work in progress to address serious performance issues when reprojecting large datasets, mainly with ``reproject_interp``.
To do:
Fixes #393 
Fixes #394
> Improve performance for large datasets and switch to multi-threading by default

- reproject/adaptive/deforest.pyx
- reproject/adaptive/tests/test_core.py
@astrofrog This is what I found for readonly arrays in Cython: https://github.com/cython/cython/pull/1869
Just need to add `const` to the types of the input arrays
Closes #449 ?
> Support readonly arrays in adaptive

- reproject/common.py
- reproject/mosaicking/coadd.py
- reproject/utils.py
@keflavich - this might help understand what reproject is doing. Probably should document this, need to do:
```
import logging
logging.basicConfig(level=logging.INFO)
```
to see any messages
> Add logging calls and fix a couple of dask-related issues

- reproject/healpix/core.py
- reproject/healpix/tests/test_healpix.py
These were due to using scipy's map_coordinates directly instead of our wrapper which deals properly with boundaries
> Fix bug with artifacts in reproject_to_healpix

- tox.ini
This pins zarr as the zarr 3.0 pre-release is very incompatible with dask. At the same time, I added back sunpy dev.
> Fix devdeps CI

- reproject/array_utils.py
Split out from #447, this is needed to make workers not use up too much memory when using dask.distributed, but doesn't quite work yet as the memmap copying doesn't seem to always work (some tests failing)
> Performance improvements for interpolation with map_coordinates

- .github/workflows/ci_workflows.yml
- .github/workflows/update-changelog.yaml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- pyproject.toml
- reproject/interpolation/tests/test_core.py
- reproject/utils.py
- tox.ini
I'm surprised I didn't run into this sooner, but this should fix the endianness issue @keflavich - can you confirm?
> Fix a bug that caused big-endian dask arrays to not be reprojected correctly

- reproject/common.py
- reproject/utils.py
I think I found the cause for the failures in #491: One is what was already mentioned in https://github.com/astropy/reproject/pull/487#pullrequestreview-2675588760, and the other is similar in `reproject/common.py`. The reason why the patch shown in #491 didn't work was that the second patch in `reproject/utils.py` was actually wrong.
I applied this PR to the Debian package (merged with #487), and now [all tests pass on s390x](https://buildd.debian.org/status/fetch.php?pkg=reproject&arch=s390x&ver=0.14.1-3&stamp=1741727132&raw=0).
Disclaimer: This is a fix by a "poor stranger". I didn't dig into the structure of reproject for this but just fixed what could cause the failures. There may be other places with a similar issue, or side effects that are not covered by the CI tests. So, please …
> Force little endian input for zarr

- reproject/mosaicking/coadd.py
- reproject/mosaicking/tests/test_coadd.py
- reproject/utils.py
I encountered a severe error case in which the weights array became NaN after reprojection.  Flagging out locations where weights is NaN solved the issue.
I cannot come up with an MWE; this occurs deep in the guts of a complicated mosaicking attempt, and it happened for only 1 field out of 270.  I think it might be the consequence of a numerical error that occurs only under unique conditions, but it also looks logically like this fix _should_ work.
> Flag out NaN weights in coadd & allow for weights to have different WCS than data

- reproject/adaptive/high_level.py
- reproject/common.py
- reproject/conftest.py
- reproject/hips/high_level.py
- reproject/interpolation/high_level.py
- reproject/interpolation/tests/test_core.py
- reproject/spherical_intersect/high_level.py
- reproject/utils.py
This removed the short-lived ``return_type='pil_image'`` (never released) because it's a bit ambiguous how we should handle the footprint, and it would make more sense for users to decide how they want to construct an RGB image with the output. We can still use RGB images with AVM as input though. I've also removed ``as_rgb_images`` which is not needed anymore.
Closes https://github.com/astropy/reproject/issues/523
> Clean up RGB code and API

- reproject/hips/high_level.py
Previously ``threads=True`` meant ``threads=1``
Fixes https://github.com/astropy/reproject/issues/525
> Fix threads=True option in reproject.hips

- reproject/mosaicking/tests/test_wcs_helpers.py
- reproject/mosaicking/wcs_helpers.py
This defaults to ``None`` which means auto. This is a break in API compared to before since for solar WCS for example, cdelt will now be positive. I'm not sure how to change the default via a deprecation phase though, so maybe we have to just bite the bullet?
Fixes https://github.com/astropy/reproject/issues/431
@svank @Cadair - any opinions?
> Add a new keyword argument ``negative_lon_cdelt`` to `find_optimal_celestial_wcs`

- pyproject.toml
For some reason the version with email was getting transformed to:
```
Author: Christoph Deil, Adam Ginsburg
Author-email: Thomas Robitaille <thomas.robitaille@gmail.com>
```
who knows :shrug:
> Fix formatting of authors and add @Cadair and @svank
